version: "3.9"

services:
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=python_sample
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:4512
    volumes:
      - .:/code
    ports:
      - 4512:4512
    depends_on:
      - db

